    - name: Install packages
      pip:
        name:
          - docker-compose
          - docker
        state: present
    - name: Git checkout
      ansible.builtin.git:
        repo: "{{ git_repository }}"
        dest: "{{ deployment_path }}"
        version: "{{ git_branch }}"
    - name: Run docker-compose up
      docker_compose:
        project_src: "{{ deployment_path }}"
        build: yes